config/routes.rb
Vagavitsa::Application.routes.draw do
  resources :jokes do
    
    member do
      post "vote"
    end

    collection do
      get "list"
      get "next"
    end

  end

  get "home/index"
  
  root :to => "home#index"

end

app/models/joke.rb
class Joke < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	redirect_to :controller => 'jokes', :action => 'next'
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jokes }
    end
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show

    @joke = Joke.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @joke }
    end

  end

  def next
    ids = Joke.find(:all).collect{ | j | j.id }
    id = ids[rand(ids.length)]
    redirect_to :action => 'show', :id => id
  end

  # GET /jokes/new
  # GET /jokes/new.json
  def new
    @joke = Joke.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @joke }
    end
  end

  # GET /jokes/1/edit
  def edit
    @joke = Joke.find(params[:id])
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(params[:joke])

    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, notice: 'Joke was successfully created.' }
        format.json { render json: @joke, status: :created, location: @joke }
      else
        format.html { render action: "new" }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jokes/1
  # PUT /jokes/1.json
  def update
    @joke = Joke.find(params[:id])

    respond_to do |format|
      if @joke.update_attributes(params[:joke])
        format.html { redirect_to @joke, notice: 'Joke was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke = Joke.find(params[:id])
    @joke.destroy

    respond_to do |format|
      format.html { redirect_to jokes_url }
      format.json { head :no_content }
    end
  end

  def vote
    @joke = Joke.find(params[:id])

    puts params

    redirect_to :action => 'next', :id => params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
	<h1>Våga Vitsa! <i>(BETA)</i></h1>
	<p>Våga Vitsa är en sida där man kan lägga upp vitsar. Andra personer kan då rösta på om de gillar en vits eller inte. Vitsar kategoriseras och visas beroende på hur många som gillar dem och hur populära de är. Varje vits har också en kommentarstråd där det går att diskutera vitsen.</p>
	<a href="#" class="btn btn-primary btn-large">Börja här!</a>
</div>

<div class="row">
	<div class="span4">
		<h2>Kul</h2>
		<p>
			Allt handlar om att hitta på roliga vitsar, bra som dåliga, alla är välkommna.
		</p>
		<a class="btn" href="#">Läs mer »</a>
	</div>

	<div class="span4">
		<h2>Enkelt</h2>
		<p>
			Klicka på <a href="#">Ny vits</a> för att lägga upp en ny vits. Eller läs andras vitsar.
		</p>
		<a class="btn" href="#">Läs mer »</a>
	</div>

	<div class="span4">
		<h2>Samarbeta</h2>
		<p>
			Hjälp varandra att komma på bättre vitsar genom att svara i kommentarsfältet på en vits.
		</p>
		<a class="btn" href="#">Läs mer »</a>
	</div>
</div>

app/views/jokes/_form.html.erb
<%= form_for(@joke) do |f| %>
  <% if @joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joke.errors.count, "error") %> gjorde att skämtet inte kunde sparas:</h2>

      <ul>
      <% @joke.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label "Skämtets uppbyggnad" %><br />
      <%= f.text_area :buildup %>
    </div>
    <div class="field">
      <%= f.label "Punchline" %><br />
      <%= f.text_area :punchline %>
    </div>
  
  <div class="actions">
    <%= f.submit "Skapa vits", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Ändra vits</h1>

<%= render 'form' %>

<%= link_to 'Visa', @joke %> |
<%= link_to 'Tillbaka', jokes_path %>

app/views/jokes/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".spoiler").hide();
    $(".punchline").click(function(){
      var parent = $(this).parent();
      parent.find(".spoiler").fadeIn();
      parent.find(".punchline").hide();
    });        
  });
</script>

<h1>Flöde</h1>

<%= link_to 'Ny vits', new_joke_path %>

<% @jokes.each do | joke |%>

<div class="well joke">
  <h2>
    <%= "\"#{joke.buildup}\"" %>
  </h2>
  <br />
  <h2 class="spoiler">
    <hr />
    <%= "\"#{joke.punchline}\"" %>
  </h2>
  <div class="punchline alert alert-info">
    <p>Klicka för punchline</p>
  </div>
</div>

<% end %>

app/views/jokes/list.html.erb
<h1>Flöde</h1>

<% @jokes.each do | joke |%>

<p>
  <b>Buildup:</b>
  <%= joke.buildup %>
</p>

<p>
  <b>Punchline:</b>
  <%= joke.punchline %>
</p>

<% end %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/new.html.erb
<h1>Ny vits</h1>

<%= render 'form' %>

<%= link_to 'Tillbaka', jokes_path %>

app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>

<script type="text/javascript">
  $(document).ready(function(){
    $(".spoiler").hide();
    $(".punchline").click(function(){
      var parent = $(this).parent();
      parent.find(".spoiler").fadeIn();
      parent.find(".punchline").hide();
    });        
  });
</script>

<div>

</div>

<div class="well joke">
  <h2>
    <%= "\"#{@joke.buildup}\"" %>
  </h2>
  <br />
  <div class="spoiler">
  <h2>
    <hr />
    <%= "\"#{@joke.punchline}\"" %>
  </h2>
  <div class="clearfix">
    <div class="actions pull-right">
      <%= form_tag :action => 'vote', :id => @joke.id do | f | %>
        <%= submit_tag 'Bra', :class => "btn btn-primary" %>
        <%= submit_tag 'Anus', :class => "btn btn-danger" %>
        <%= submit_tag 'Nästa', :class => "btn btn-info" %>
      <% end %>
    </div>
  </div>
  </div>

  <div class="punchline alert alert-info">
    <p>Klicka för punchline</p>
  </div>  
</div>

<div class="container">
	<div class="span16 offset3">
	<div class="fb-comments" data-href="http://vagavitsa.se/jokes/<%= @joke.id %>" data-num-posts="10"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Våga Vitsa!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "2cde85e2-8ccb-45d7-8dfd-dcef2387459d"}); </script>

</head>
<body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/sv_SE/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
    <ul class="nav">
		  <li class="active">
		    <a href="/" class="brand">Våga Vitsa</a>
		  </li>
      <li><%= link_to 'Ny vits', :controller => 'jokes', :action => 'new' %></li>
		</ul>
    <ul class="nav pull-right">
		    <li><a href="#">Logga in</a></li>
    </ul>
    </div>
  </div>
</div>

<div class="container" style="margin-top:60px;">
	<%= yield %>
</div>

<hr />

<div class="container">
  <div class="span14 offset2 well">
  <span class='st_sharethis_hcount' displayText='Dela detta'></span>
  <span class='st_facebook_hcount' displayText='Facebook'></span>
  <span class='st_fblike_hcount' displayText='Gilla'></span>
  <span class='st_fbrec_hcount' displayText='Rekommendera'></span>
  <span class='st_twitter_hcount' displayText='Tweeta'></span>
  <span class='st_googleplus_hcount' displayText='Google +'></span>
  <span class='st_pinterest_hcount' displayText='Pinterest'></span>
  </div>
</div>

<hr />

<div class="container">
  <div class="offset4">
	<p>Copyright &copy; Erik Skoglund & Adam Hall 2012 - <%= Time.new.year %></p>
  </div>
</div>

</body>
</html>